name: $(SourceBranchName)_$(date:yyyy/MMdd)$(rev:.r)_PerilsProximity_Configs_Update
  
trigger:
- master

variables:
  time: $[ format('{0:yyyy}-{0:MM}-{0:dd}-{0:HHmm}', pipeline.startTime) ]

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Getting latest config files 
  displayName: 'Run a one-line script'



- task: CopyFiles@2
  displayName: 'Copy Staging Config  Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      staging/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PnP-Config-Drop-staging-$(time)

- task: CopyFiles@2
  displayName: 'Copy Pr-prod Config Staging Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      preprod/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: PnP-Config-Drop-preprod-$(time)


- task: CopyFiles@2
  displayName: 'Copy Fint Config Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      fint/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName:  PnP-Config-Drop-fint-$(time)

- task: CopyFiles@2
  displayName: 'Copy Prod Config Files  to: $(Build.ArtifactStagingDirectory)'
  inputs:
      contents: |
        prod/Web.config
        batch.exe.config
        deploy_config.ps1
      targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName:  'PnP-Config-Drop-prod-$(time)'
