# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  -environment:
    -v
  time: $[ format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime) ]
  pwsh_time: $(Get-Date -Date $(time) -Format yyyy.MMM.dd)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  displayName: 'Copy Staging Config  Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      staging/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Prelis-Config-Drop-staging

- task: CopyFiles@2
  displayName: 'Copy Pr-prod Config Staging Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      preprod/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Prelis-Config-Drop-preprod


- task: CopyFiles@2
  displayName: 'Copy Fint Config Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: |
      fint/Web.config
      batch.exe.config
      deploy_config.ps1
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName:  Prelis-Config-Drop-fint

- task: CopyFiles@2
  displayName: 'Copy Prod Config Files  to: $(Build.ArtifactStagingDirectory)'
  inputs:
      contents: |
        prod/Web.config
        batch.exe.config
        deploy_config.ps1
      targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName:  Prelis-Config-Drop-prod-$(pwsh_time)
