name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)_PerilsProximity_Build_Configs

#Pipeline actions:
# select environment and config files are copied to the machin destination
# variable group is picked from selected environment
# actual deployment is done after manual approval
# stops, services
# deploys
# starts services
# for pre-prod & prod, this is repeated for all the machines 



trigger:
  - config-pipeline
  - master

appendCommitMessageToRunName: false

pool:
  vmImage: windows-latest

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: staging
    values:
    - staging
    - fint
    - preprod
    - production

variables:
- group: PerilsProximity.Configs.${{ parameters.environment }} # note there's a dash at the beginning of the line
- name: time
  value: $[ format('{0:yyyy}-{0:MM}-{0:dd}-{0:HHmm}', pipeline.startTime) ]
- name: varname2
  value: value2
- name: artifactName
  value: PnP-Config-Drop-${{ parameters.environment }}


jobs:
- job: CopyConfigFilesToEnvironment
  displayName: Copy configs to target environment 
  steps:
    - task: CopyFiles@2
      displayName: 'Copy ${{ parameters.environment }} config  files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        contents: |
          ${{ parameters.environment }}/config/batch.config
          ${{ parameters.environment }}/config/BatchProcessorService.exe.config
          ${{ parameters.environment }}/config/BatchProcessor_Log.config
          ${{ parameters.environment }}/config/BatchSubmissionService.exe.config
          ${{ parameters.environment }}/config/BatchSubmission_log.config
          ${{ parameters.environment }}/config/BatchWebTestHarness.exe.config
          ${{ parameters.environment }}/config/Create_Message.exe.config
          ${{ parameters.environment }}/config/MQListener.exe.config
          ${{ parameters.environment }}/config/TEst_App.exe.config
          ${{ parameters.environment }}/config/BatchManager/Web.config
          ${{ parameters.environment }}/config/BatchStatus/Web.config
          ${{ parameters.environment }}/config/BestAddress/Web.config
          ${{ parameters.environment }}/config/Geoassessment/Web.config
          ${{ parameters.environment }}/config/GlobalExposure/Web.config
          ${{ parameters.environment }}/config/LocatorHubWS/Web.config
          ${{ parameters.environment }}/config/PerilsPlusWS/Web.config
          utilities/deploy_config.ps1
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PowerShell@2
      displayName: 'Move deploy_config script'
      inputs:
        targetType: 'inline'
        script: |
          Move-Item -Path $(Build.ArtifactStagingDirectory)/utilities/deploy_config.ps1 -Destination $(Build.ArtifactStagingDirectory)/${{ parameters.environment }}/deploy_config.ps1
    - task: CmdLine@2
      displayName: b4 publishing, display tree of build artifact from $(Build.ArtifactStagingDirectory) 
      inputs:
        script: |
          echo ##[debug]List of built in variables in Build.ArtifactStagingDirectory 
          tree $(Build.ArtifactStagingDirectory) /F
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: $(artifactName)

    # Download build artifacts v1
    # Download files that were saved as artifacts of a completed build.
    - task: DownloadBuildArtifacts@1
      displayName: 'Download artifact'
      inputs:
        buildType: 'current' # 'current' | 'specific'. Required. Download artifacts produced by. Default: current.
        buildVersionToDownload: 'latest' # 'latest' | 'latestFromBranch' | 'specific'. Required when buildType == specific. Build version to download. Default: latest.
        downloadType: 'single' # 'single' | 'specific'. Required. Download type. Default: single.
        artifactName: $(artifactName) # string. Required when downloadType == single. Artifact name. 
        downloadPath: $(System.ArtifactsDirectory) # string. Required. Destination directory. Default: $(System.ArtifactsDirectory).
        cleanDestinationFolder: true # boolean. Clean destination folder. Default: false.
        checkDownloadedFiles: true # boolean. Check downloaded files. Default: false.
    - task: CmdLine@2
      displayName: Display tree of sytem artifact dir from $(System.ArtifactsDirectory)
      inputs:
        script: |
            echo ##[debug]List of built in variables in System.ArtifactsDirectory 
            tree $(System.ArtifactsDirectory) /F
    - task: CopyFilesOverSSH@0
      displayName: 'Copy files from $(System.ArtifactsDirectory) to server via SSH to target environment $(deployment_ssh_connection)'
      inputs:
        sshEndpoint: $(deployment_ssh_connection)
        sourceFolder: $(System.ArtifactsDirectory)
        contents: '**'
        targetFolder: 'C:\PnPConfigsDeployment\'
        isWindowsOnTarget: true
        cleanTargetFolder: true
        readyTimeout: '20000'
        overwrite: true
        failOnEmptySource: true      

- job: ApproveDeployment
  displayName: Wait for manual approval 
  dependsOn: CopyConfigFilesToEnvironment
  timeoutInMinutes: 4320 # job times out in 3 days
  pool: server 
  steps:   
  - task: ManualValidation@1
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
      notifyUsers: |
        itai.dhliwayo@gmail.com
      instructions: 'Please validate the build drop and resume deployment'
      allowApproversToApproveTheirOwnRuns: true
      onTimeout: 'reject'

- job: Deploy
  displayName: Deploy in target environment
  dependsOn: ApproveDeployment
  steps:
    - task: PowerShellOnTargetMachines@3
      inputs:
        Machines: $(hostname) # string. Required. Machines. 
        UserName: $(username) # string. Username. 
        UserPassword: $(password) # string. Password. 
      # Script options
        ScriptType: 'FilePath' # 'FilePath' | 'Inline'. Script Type. Default: Inline.
        ScriptPath: 'C:\PnPConfigsDeployment\$(artifactName)\${{ parameters.environment }}\deploy_config.ps1' # string. Required when ScriptType = FilePath. Script File Path. 
        InlineScript: # string. Required when ScriptType = Inline. Script. 
        #ScriptArguments: # string. Optional. Use when ScriptType = FilePath. Script Arguments. 
        #InitializationScript: # string. Optional. Use when ScriptType = FilePath. Initialization script. 
        #SessionVariables: # string. Optional. Use when ScriptType = FilePath. Session Variables. 
      # PSSession options
        #CommunicationProtocol: 'Https' # 'Http' | 'Https'. Protocol. Default: Https.
        #AuthenticationMechanism: 'Default' # 'Default' | 'Credssp'. Authentication. Default: Default.
        #NewPsSessionOptionArguments: '-SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block' # string. Session Option parameters. Default: -SkipCACheck -IdleTimeout 7200000 -OperationTimeout 0 -OutputBufferingMode Block.
      # Error handling options
        #ErrorActionPreference: 'stop' # 'stop' | 'continue' | 'silentlyContinue'. ErrorActionPreference. Default: stop.
        #failOnStderr: false # boolean. Fail on Standard Error. Default: false.
        #ignoreLASTEXITCODE: false # boolean. Ignore $LASTEXITCODE. Default: false.
      # Advanced
        #WorkingDirectory: # string. Working Directory. 
        #RunPowershellInParallel: true # boolean. Run PowerShell in Parallel. Default: true.   
  # - task: SSH@0
  #   displayName: 'Run deployment script via SSH on target environment $(deployment_ssh_connection)'
  #   inputs:
  #     sshEndpoint: $(deployment_ssh_connection)
  #     runOptions: 'commands'
  #     commands: |
  #       C:\PnPConfigsDeployment\$(artifactName)\${{ parameters.environment }}\deploy_config.ps1
  #     failOnStdErr: true 
  #     readyTimeout: '20000'


  

 
